services:
  pg-primary:
    # Using 'latest' because only this tag is available in your registry/Docker Hub view
    image: bitnami/postgresql:latest
    container_name: pg-primary
    restart: unless-stopped
    environment:
      # Basis-DB (App-User optional)
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_password
      - POSTGRESQL_DATABASE=appdb
      # Superuser (postgres)
      - POSTGRESQL_POSTGRES_PASSWORD=supersecret
      # Replikation
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_secret
      # Synchronie: 1 synchrone Replica, Commit wartet auf deren Bestätigung
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      # remote_apply = am strengsten (WAL angewendet auf Replica)
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=remote_apply
      # application_name, auf das sich synchronous_standby_names referenziert
      - POSTGRESQL_CLUSTER_APP_NAME=replica1
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_primary_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=app_password pg_isready -U app -d appdb -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [pgnet]

  pg-replica:
    # Using 'latest' to match availability in your registry
    image: bitnami/postgresql:latest
    container_name: pg-replica
    restart: unless-stopped
    depends_on:
      pg-primary:
        condition: service_healthy
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_secret
      # Muss mit dem Namen im Primary (CLUSTER_APP_NAME) zusammenpassen
      - POSTGRESQL_CLUSTER_APP_NAME=replica1
      # Optional: nur lesen zulassen (Standard der Replica ist bereits read-only)
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "127.0.0.1:5433:5432" # Zugriff auf die Read-Replica über 5433
    volumes:
      - pg_replica_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=repl_secret pg_isready -U repl_user -d postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [pgnet]

networks:
  pgnet:

volumes:
  pg_primary_data:
  pg_replica_data: